#Requires -Modules Microsoft.Graph.Users, Microsoft.Graph.Identity.Governance, Microsoft.Graph.Identity.DirectoryManagement

<#
.SYNOPSIS
    Restores direct Entra directory role assignments that were removed by Add-UserToPIMGroup.ps1.

.DESCRIPTION
    Reads a rollback JSON file generated by Add-UserToPIMGroup.ps1 and re-assigns
    all previously removed directory roles as permanent active assignments.

    Optionally removes the PIM-eligible group membership that was added.

.PARAMETER RollbackFile
    Path to the rollback JSON file (found in the Rollback\ folder).

.PARAMETER RemoveGroupEligibility
    If specified, also removes the PIM-eligible membership from the security group.

.EXAMPLE
    # List available rollback files
    Get-ChildItem .\Rollback\*.json

    # Restore roles from a specific rollback file
    .\Restore-UserRoles.ps1 -RollbackFile ".\Rollback\user@contoso.com_20260502_173000.json"

    # Restore roles AND remove the PIM group eligibility
    .\Restore-UserRoles.ps1 -RollbackFile ".\Rollback\user@contoso.com_20260502_173000.json" -RemoveGroupEligibility

.NOTES
    Requires Microsoft Graph PowerShell SDK.
    You must be a Privileged Role Administrator or Global Administrator.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$RollbackFile,

    [switch]$RemoveGroupEligibility
)

$ErrorActionPreference = "Stop"

# ── 1. Load rollback data ────────────────────────────────────────────────────
Write-Host "`n[1/4] Loading rollback data..." -ForegroundColor Cyan

$rollback = Get-Content -Path $RollbackFile -Raw | ConvertFrom-Json

if (-not $rollback.UserPrincipalName -or -not $rollback.RemovedAssignments) {
    throw "Invalid rollback file. Missing required fields."
}

Write-Host "  User      : $($rollback.DisplayName) ($($rollback.UserPrincipalName))" -ForegroundColor Green
Write-Host "  Group     : $($rollback.GroupName)" -ForegroundColor Green
Write-Host "  Removed at: $($rollback.Timestamp)" -ForegroundColor Green
Write-Host "  Roles     : $($rollback.RemovedAssignments.Count) assignment(s) to restore`n" -ForegroundColor Green

# ── 2. Connect to Microsoft Graph ────────────────────────────────────────────
$requiredScopes = @(
    "User.Read.All",
    "RoleManagement.ReadWrite.Directory",
    "PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup"
)

Write-Host "[2/4] Connecting to Microsoft Graph..." -ForegroundColor Cyan
Connect-MgGraph -Scopes $requiredScopes -ErrorAction Stop
Write-Host "  Connected.`n" -ForegroundColor Green

# ── 3. Verify the user still exists ─────────────────────────────────────────
Write-Host "[3/4] Verifying user..." -ForegroundColor Cyan

$user = Get-MgUser -UserId $rollback.UserPrincipalName -ErrorAction Stop
if ($user.Id -ne $rollback.UserId) {
    throw "User ID mismatch. The UPN '$($rollback.UserPrincipalName)' now resolves to a different user."
}
Write-Host "  User verified: $($user.DisplayName) [Id: $($user.Id)]`n" -ForegroundColor Green

# ── 4. Restore each role assignment ─────────────────────────────────────────
Write-Host "[4/4] Restoring direct active role assignments..." -ForegroundColor Cyan

$restored = 0
$failed   = 0

foreach ($entry in $rollback.RemovedAssignments) {
    $roleName = $entry.RoleName
    if (-not $roleName) { $roleName = $entry.RoleDefinitionId }

    # Check if this assignment already exists (idempotent)
    $existing = Get-MgRoleManagementDirectoryRoleAssignmentScheduleInstance `
        -Filter "principalId eq '$($user.Id)' and roleDefinitionId eq '$($entry.RoleDefinitionId)'" `
        -ErrorAction SilentlyContinue |
        Where-Object { $_.DirectoryScopeId -eq $entry.DirectoryScopeId -and $_.MemberType -eq "Direct" }

    if ($existing) {
        Write-Host "  [SKIP] '$roleName' already assigned. Skipping." -ForegroundColor DarkYellow
        $restored++
        continue
    }

    if ($PSCmdlet.ShouldProcess($user.DisplayName, "Restore direct role '$roleName'")) {
        try {
            $assignParams = @{
                Action           = "adminAssign"
                PrincipalId      = $user.Id
                RoleDefinitionId = $entry.RoleDefinitionId
                DirectoryScopeId = $entry.DirectoryScopeId
                Justification    = "Rollback - restoring direct assignment removed by Add-UserToPIMGroup"
                ScheduleInfo     = @{
                    Expiration = @{
                        Type = "noExpiration"
                    }
                }
            }

            New-MgRoleManagementDirectoryRoleAssignmentScheduleRequest `
                -BodyParameter $assignParams -ErrorAction Stop | Out-Null
            Write-Host "  [OK] Restored: $roleName (scope: $($entry.DirectoryScopeId))" -ForegroundColor Green
            $restored++
        }
        catch {
            Write-Host "  [ERROR] Failed to restore '$roleName': $($_.Exception.Message)" -ForegroundColor Red
            $failed++
        }
    }
}

# ── Optional: Remove PIM group eligibility ───────────────────────────────────
if ($RemoveGroupEligibility) {
    Write-Host "`nRemoving PIM-eligible membership from '$($rollback.GroupName)'..." -ForegroundColor Cyan

    $eligibility = Get-MgIdentityGovernancePrivilegedAccessGroupEligibilityScheduleInstance `
        -Filter "groupId eq '$($rollback.GroupId)' and principalId eq '$($user.Id)'" `
        -ErrorAction SilentlyContinue

    if (-not $eligibility) {
        Write-Host "  No eligible membership found. Nothing to remove." -ForegroundColor DarkYellow
    }
    else {
        if ($PSCmdlet.ShouldProcess($user.DisplayName, "Remove PIM eligibility from '$($rollback.GroupName)'")) {
            try {
                $removeParams = @{
                    AccessId      = "member"
                    PrincipalId   = $user.Id
                    GroupId       = $rollback.GroupId
                    Action        = "adminRemove"
                    Justification = "Rollback - removing eligible membership added by Add-UserToPIMGroup"
                }

                New-MgIdentityGovernancePrivilegedAccessGroupEligibilityScheduleRequest `
                    -BodyParameter $removeParams -ErrorAction Stop | Out-Null
                Write-Host "  [OK] Eligible membership removed from '$($rollback.GroupName)'." -ForegroundColor Green
            }
            catch {
                Write-Host "  [ERROR] Failed to remove eligibility: $($_.Exception.Message)" -ForegroundColor Red
            }
        }
    }
}

Write-Host "`n=== Rollback Complete ===" -ForegroundColor Cyan
Write-Host @"

Summary for $($user.DisplayName):
  - Roles restored : $restored
  - Failures       : $failed
  - Group eligibility removed: $(if ($RemoveGroupEligibility) { 'Yes' } else { 'No (use -RemoveGroupEligibility to remove)' })
"@
